LigaNos/LigaNOS (2)/LigaNOS/LigaNOS/Models/NotFoundViewModel.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Net;

namespace LigaNOS.Models
{
    public class NotFoundViewModel : ViewResult
    {

     public NotFoundViewModel(string viewName)
        {
            ViewName = viewName;
            StatusCode = (int)HttpStatusCode.NotFound;
        }
    }
}

LigaNos/LigaNOS (2)/LigaNOS/LigaNOS/Controllers/ClubsController.cs
using LigaNOS.Data;
using LigaNOS.Data.Entities;
using LigaNOS.Data.Repositories;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;
using LigaNOS.Helpers;
using LigaNOS.Models;
using System;
using System.Security.Cryptography;
using Microsoft.AspNetCore.Authorization;

namespace LigaNOS.Controllers
{

    public class ClubsController : Controller
    {
        private readonly IClubRepository _clubRepository;
        private readonly IUserHelper _userHelper;
        private readonly IConverterHelper _converterHelper;
        private readonly IBlobHelper _blobHelper;
        public ClubsController(IClubRepository clubRepository, IUserHelper userHelper, IConverterHelper converterHelper, IBlobHelper blobHelper)
        {
            _clubRepository = clubRepository;
            _userHelper = userHelper;
            _converterHelper = converterHelper;
            _blobHelper = blobHelper;
        }

        // GET: ClubsController

        public IActionResult Index()
        {
            return View(_clubRepository.GetAll().OrderBy(c => c.Name));
        }

        // GET: ClubsController/Details/5
        [Authorize(Roles = "Admin, Club")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new NotFoundViewModel("ClubNotFound");
            }

            // var club = await _clubRepository.GetByIdAsync(id.Value);
            var club = await _clubRepository.GetAll()
                    .Include(c => c.Players) // Incluir jogadores
                    .FirstOrDefaultAsync(c => c.Id == id.Value);


            if (club == null)
            {
                return new NotFoundViewModel("ClubNotFound");
            }

            return View(club);
        }

        // GET: ClubsController/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();

        }

        // POST: ClubsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ClubViewModel model)
        {
            var existingClub = await _clubRepository.GetAll()
           .FirstOrDefaultAsync(c => c.Name.ToLower() == model.Name.ToLower());

            if (existingClub != null)
            {
                ModelState.AddModelError(string.Empty, "Club already registed.");
                return View(model);
            }
            if (ModelState.IsValid)
            {
                Guid imageId = Guid.Empty;

                if (model.ImageFile != null && model.ImageFile.Length > 0)
                {
                    imageId = await _blobHelper.UploadBlobAsync(model.ImageFile, "clubs");

                }
                var club = _converterHelper.ToClub(model, imageId, true);

                if (!User.Identity.IsAuthenticated)
                {
                    return RedirectToAction("Login", "Account");
                }

                club.User = await _userHelper.GetUserByEmailAsync(this.User.Identity.Name);


                await _clubRepository.CreateAsync(club);
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        // GET: ClubsController/Edit/5
        [Authorize(Roles = "Admin ")]
        public async Task<IActionResult> Edit(int id)
        {

            var club = await _clubRepository.GetByIdAsync(id);
            if (club == null)
            {
                return new NotFoundViewModel("ClubNotFound");
            }
            var model = _converterHelper.ToClubViewModel(club);
            return View(model);

        }

        // POST: ClubsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, ClubViewModel model)
        {
            if (id != model.Id)
            {
                return new NotFoundViewModel("ClubNotFound");
            }

            if (ModelState.IsValid)
            {
                if (!User.Identity.IsAuthenticated)
                {
                    return RedirectToAction("Login", "Account");
                }

                try
                {
                    var club = await _clubRepository.GetByIdAsync(model.Id);
                    if (club == null)
                    {
                        return new NotFoundViewModel("ClubNotFound");
                    }
                    //check image
                    if (model.ImageFile != null && model.ImageFile.Length > 0)
                    {
                        club.ImageFileId = await _blobHelper.UploadBlobAsync(model.ImageFile, "clubs");
                    }


                    club.Name = model.Name;
                    club.Coach = model.Coach;
                    club.Stadium = model.Stadium;

                    club.User = await _userHelper.GetUserByEmailAsync(User.Identity.Name);

                    await _clubRepository.UpdateAsync(club);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await _clubRepository.ExistAsync(model.Id))
                    {
                        return new NotFoundViewModel("ClubNotFound");
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        // GET: ClubsController/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new NotFoundViewModel("ClubNotFound");
            }

            var club = await _clubRepository.GetByIdAsync(id.Value);

            if (club == null)
            {
                return new NotFoundViewModel("ClubNotFound");
            }

            return View(club);
        }

        // POST: ClubsController/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var club = await _clubRepository.GetByIdAsync(id);
            if (club == null)
            {
                return new NotFoundViewModel("ClubNotFound");
            }

            var hasMatches = await _clubRepository.HasMatchesAsync(id);

            if (hasMatches)
            {
                ModelState.AddModelError(string.Empty, "Cannot delete this club because there are matches associated.");
                return View(club);
            }

            await _clubRepository.DeleteAsync(club);
            return RedirectToAction(nameof(Index));
        }
        public IActionResult ClubNotFound()
        {
            return View();
        }
    }
}

LigaNos/LigaNOS (2)/LigaNOS/LigaNOS/Controllers/ContactsController.cs
using LigaNOS.Data;
using LigaNOS.Data.Entities;
using LigaNOS.Helpers;
using LigaNOS.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Vereyon.Web;

namespace LigaNOS.Controllers
{
    public class ContactsController : Controller 
    { 

    private readonly IMailHelper _mailHelper;
    private readonly IFlashMessage _flashMessage;
    private readonly DataContext _context;
        public ContactsController(IMailHelper mailHelper,
            IFlashMessage flashMessage,
            DataContext context)
        {
            _mailHelper = mailHelper;
            _flashMessage = flashMessage;
            _context = context;
        }
        // GET: ContactsController
        public ActionResult Index()
        {

            return View(new ContactViewModel());
        }


        [HttpPost]
        public async Task<IActionResult> SendMail(ContactViewModel model)
        {
            if (ModelState.IsValid)
            {
                Response response = _mailHelper.SendEmail("ritapereiramiguens@gmail.com", model.Subject, model.Message);

            
                var contact = new Contact
                {
                    Name = model.Name,
                    Email = model.Email,
                    Subject = model.Subject,
                    Message = model.Message
                };

                _context.Contacts.Add(contact);
                await _context.SaveChangesAsync();

                if (response.IsSuccess)
                {
                    _flashMessage.Confirmation("Message sent!");
                    return RedirectToAction("Index");
                }
                else
                {
                    _flashMessage.Danger("Error! Message not sent.");
                }
            }
            return View("Index", model);
        }
    }
}

LigaNos/LigaNOS (2)/LigaNOS/LigaNOS/Controllers/StatsController.cs
using LigaNOS.Data.Repositories;
using LigaNOS.Helpers;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using LigaNOS.Models;
using System.Linq;
using LigaNOS.Data.Entities;
using LigaNOS.Data;
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Authorization;
namespace LigaNOS.Controllers
{
    public class StatsController : Controller
    {
        private readonly IStatRepository _statRepository;
        private readonly IMatchRepository _matchRepository;
        private readonly IClubRepository _clubRepository;
        private readonly IUserHelper _userHelper;
        private readonly IConverterHelper _converterHelper;
        private readonly IBlobHelper _blobHelper; 
        private readonly DataContext _context;
        public StatsController(IStatRepository statRepository, IMatchRepository matchRepository, IClubRepository clubRepository, IUserHelper userHelper, IConverterHelper converterHelper, IBlobHelper blobHelper, DataContext dataContext)
        {
            _statRepository = statRepository;
            _matchRepository = matchRepository;
            _clubRepository = clubRepository;
            _userHelper = userHelper;
            _converterHelper = converterHelper;
            _blobHelper = blobHelper;
             
            _context = dataContext;
        }
        // GET: StatsController
        
        public ActionResult Index()
        {
            if (_matchRepository == null)
            {
                throw new InvalidOperationException("_matchRepository is not initialized.");
            }
            var matches = _matchRepository.GetAllWithUsers()
                .OfType<Match>()
                .Include(m => m.HomeClub)
                .Include(m => m.AwayClub)
                .Select(m => new MatchViewModel
                {
                    HomeClub = m.HomeClub.Name,
                    AwayClub = m.AwayClub.Name,
                    HomeGoals = m.HomeGoals,
                    AwayGoals = m.AwayGoals,
                    MatchDay = m.MatchDay,
                    MatchTime = m.MatchTime,
                    Stadium = m.Stadium
                })
                .ToList();
            var clubs = _clubRepository.GetAllWithUsers().OfType<Club>().ToList();
            var clubStats = new List<ClubStatViewModel>();
            if (clubStats == null)
            {
                throw new InvalidOperationException("No club stats found.");
            }
            foreach (var club in clubs)
            {
                var matchesForClub = _context.Matches
                    .Where(m => m.HomeClub.Id == club.Id || m.AwayClub.Id == club.Id)
                    .ToList();

                int wins = 0;
                int losses = 0;
                int draws = 0;

                var points = 0;
                var goalsScored = 0;
                var goalsConceded = 0;

                foreach (var match in matchesForClub) //count points, goals, wins, losses, draws
                {
                    bool isHomeTeam = match.HomeClub.Id == club.Id;

                    if (isHomeTeam)
                    {
                        goalsScored += match.HomeGoals;
                        goalsConceded += match.AwayGoals;

                        if (match.HomeGoals > match.AwayGoals)
                        {
                            points += 3;
                            wins++;
                        }
                        else if (match.HomeGoals == match.AwayGoals)
                        {
                            points += 1;
                            draws++;
                        }
                        else
                        {
                            losses++;
                        }
                    }
                    else
                    { 
                        goalsScored += match.AwayGoals;
                        goalsConceded += match.HomeGoals;

                        if (match.AwayGoals > match.HomeGoals)
                        {
                            points += 3;
                            wins++;
                        }
                        else if (match.AwayGoals == match.HomeGoals)
                        {
                            points += 1;
                            draws++;
                        }
                        else
                        {
                            losses++;
                        }
                    }
                }

                clubStats.Add(new ClubStatViewModel
                {
                    ClubName = club.Name,
                    Points = points,
                    GoalsScored = goalsScored,
                    GoalsConceded = goalsConceded,
                    Wins = wins,
                    Losses = losses,
                    Draws = draws,
                    ClubSymbol = club.ImageFileId
                });
            }
            var model = new StatViewModel
            {
                MatchResults = matches,
                ClubStats = clubStats
            };
            return View(model);

        }


        // GET: StatsController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }
        // GET: StatsController/Create
        public ActionResult Create()
        {
            return View();
        }
        // POST: StatsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        // GET: StatsController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }
        // POST: StatsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        // GET: StatsController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }
        // POST: StatsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

LigaNos/LigaNOS (2)/LigaNOS/LigaNOS/Views/Shared/NotFound.cshtml
@{
    ViewData["Title"] = "NotFound";
}

LigaNos/LigaNOS (2)/LigaNOS/LigaNOS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LigaNOS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LigaNOS</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About...</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contacts" asp-action="Index">Contacts</a>
                        </li>
                     
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        @if (this.User.Identity.IsAuthenticated && this.User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Admin </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Employees" asp-action="Index">Employees</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Account" asp-action="RegisterRole">New Role </a></li>
                                  

                                </ul>
                            </li>
                        }
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        @if (this.User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="ChangeUser">@this.User.Identity.Name</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>

                        }

                         
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Players" asp-action="Index">Players</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Clubs" asp-action="Index">Clubs</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Matches" asp-action="Index">Matches</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Stats" asp-action="Index">Results</a>
                        </li>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - LigaNOS -  <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

 